
# =================================================================== #
#                            DUO SETTINGS                             #
# =================================================================== #

# Go into Duo.com account and protect a new Auth API application
# Place the generated values into here
ikey: DIXXXXXXXXXXXXXXXXXX
skey: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
apihost: api-XXXXXXXX.duosecurity.com
